//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antique.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Antiqe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Antiqe()
        {
            this.Buys = new HashSet<Buy>();
        }

        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{Photo}";
            }
        }

        public string GetAvaible
        {
            get
            {
                if (Presence == 1)
                {
                    return "В наличии";
                }
                else
                {
                    return "Нет в наличии";
                }
            }
        }

        public int AntiquesID { get; set; }
        public string Author { get; set; }
        public int Presence { get; set; }
        public double Price { get; set; }
        public string ProdCount { get; set; }
        public string ProdYear { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buys { get; set; }
    }
}
