//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antique.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int BuyID { get; set; }
        public int AntiquesID { get; set; }
        public System.DateTime BuyDate { get; set; }
        public int ClientID { get; set; }
    
        public virtual Antiqe Antiqe { get; set; }
        public virtual Client Client { get; set; }
    }
}
