//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antique.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntiquesShopEntities : DbContext
    {
        public AntiquesShopEntities()
            : base("name=AntiquesShopEntities")
        {
        }

        static private AntiquesShopEntities _ctx;
        static public AntiquesShopEntities GetContext() => _ctx ?? (_ctx = new AntiquesShopEntities());

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antiqe> Antiqes { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Buy> Buys { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
