//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_pokypok
    {
        public int History_pokypok_ID { get; set; }
        public int Tovar_ID { get; set; }
        public System.DateTime Data_pokyp { get; set; }
        public int Kolich_kuplen_produkcii { get; set; }
        public int Sotrudnik_ID { get; set; }
        public int Yslyga_ID { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual Yslyga Yslyga { get; set; }
    }
}
