//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klient()
        {
            this.Skan = new HashSet<Skan>();
            this.Zapis_klienta = new HashSet<Zapis_klienta>();
        }
    
        public int Klient_ID { get; set; }
        public string Famil { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public System.DateTime Data_rogenie { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Pol { get; set; }
        public System.DateTime Data_registr { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skan> Skan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis_klienta> Zapis_klienta { get; set; }
    }
}
