//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagazEntities : DbContext
    {
        public MagazEntities()
            : base("name=MagazEntities")
        {
        }

        private static MagazEntities _context;

        public static MagazEntities GetContext()
        {
            if (_context == null)
            {
                _context = new MagazEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History_pokypok> History_pokypok { get; set; }
        public virtual DbSet<Kategor_tovara> Kategor_tovara { get; set; }
        public virtual DbSet<Kategoriya_spec> Kategoriya_spec { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Skan> Skan { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Tovar_sezon> Tovar_sezon { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Yslyga> Yslyga { get; set; }
        public virtual DbSet<Zapis_klienta> Zapis_klienta { get; set; }
    }
}
