//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skan
    {
        public int Skan_ID { get; set; }
        public int Klient_ID { get; set; }
        public int Nomer_pasporta { get; set; }
        public int Seriya_pasporta { get; set; }
        public string Photo_pasporta { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
