//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int Sklad_ID { get; set; }
        public int Tovar_ID { get; set; }
        public int Shtrih_kod_tovara { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
