//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.History_pokypok = new HashSet<History_pokypok>();
        }
    
        public int Sotrudnik_ID { get; set; }
        public string Surename { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public string Seriya_pasporta { get; set; }
        public string Nomer_pasporta { get; set; }
        public int Kod_podrazdel { get; set; }
        public string Pol { get; set; }
        public double Koficent_oplat { get; set; }
        public System.DateTime Data_rogenie { get; set; }
        public int Kategoriya_spec_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_pokypok> History_pokypok { get; set; }
        public virtual Kategoriya_spec Kategoriya_spec { get; set; }
    }
}
