//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.History_pokypok = new HashSet<History_pokypok>();
            this.Sklad = new HashSet<Sklad>();
            this.Tovar_sezon = new HashSet<Tovar_sezon>();
        }
    
        public int Tovar_ID { get; set; }
        public string Naimenovanie { get; set; }
        public int Kategor_tovara_ID { get; set; }
        public double Stoimost { get; set; }
        public string Harakter { get; set; }
        public string Opis_tovara { get; set; }
        public double Ves { get; set; }
        public double Shirina { get; set; }
        public double Visota { get; set; }
        public double Dlina { get; set; }
        public string Proizvoditel { get; set; }
        public string Photo { get; set; }
        public string Dop_photo { get; set; }
        public bool Imeet_na_sklade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_pokypok> History_pokypok { get; set; }
        public virtual Kategor_tovara Kategor_tovara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad> Sklad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovar_sezon> Tovar_sezon { get; set; }
    }
}
