//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar_sezon
    {
        public int Tovar_sezon_ID { get; set; }
        public int Tovar_ID { get; set; }
        public bool Dostypen { get; set; }
        public System.DateTime Sezon_Dostyp_Nedostyp { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
