//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Yslyga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yslyga()
        {
            this.History_pokypok = new HashSet<History_pokypok>();
            this.Zapis_klienta = new HashSet<Zapis_klienta>();
        }

        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\image\" + Photo.Trim();

            }
        }

        public int GetSale
        {
            get
            {
                if (Skidka == 0.05)
                {
                    return 5;
                }
                else if (Skidka == 0.1)
                {
                    return 10;
                }
                else if (Skidka == 0.15)
                {
                    return 15;
                }
                else if (Skidka == 0.2)
                {
                    return 20;
                }
                else if (Skidka == 0.25)
                {
                    return 25;
                }

                else
                {
                    return 0;
                }
            }
        }

        public double GetPrice
        {
            get
            {
                if (GetSale > 0)
                {
                    return Stoimost * (1 - (GetSale * 0.01));
                }
                else
                {
                    return Stoimost;
                }
            }
        }

        public string GetColor
        {
            get
            {
                if (Skidka > 0)
                    return "#90EE90";
                else
                    return "#ffffff";
            }
        }


        public int Yslyga_ID { get; set; }
        public string Naimenovanie { get; set; }
        public string Podrob_opis { get; set; }
        public double Stoimost { get; set; }
        public Nullable<double> Skidka { get; set; }
        public double Prodolgit { get; set; }
        public string Photo { get; set; }
        public string Dop_photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_pokypok> History_pokypok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapis_klienta> Zapis_klienta { get; set; }
    }
}
