//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis_klienta
    {
        public int Zapis_klienta_ID { get; set; }
        public int Klient_ID { get; set; }
        public int Yslyga_ID { get; set; }
        public System.TimeSpan Vremya_nachala_yslygi { get; set; }
        public System.DateTime Data_nachala_yslygi { get; set; }
        public string Koment { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Yslyga Yslyga { get; set; }
    }
}
