//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addvesting.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfomance
    {
        public int PerfomanceID { get; set; }
        public System.DateTime DeciderDate { get; set; }
        public int ServiceID { get; set; }
        public int ClientID { get; set; }
        public int EmployeeID { get; set; }
        public int Performed { get; set; }
    
        public string GetPerf
        {
            get
            {
                if (Performed == 1)
                {
                    return "Выполнено";
                }
                else
                {
                    return "Не выполнено";
                }
            }
        }

        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
