//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stayEntities : DbContext
    {
        static private stayEntities _ctx;
        static public stayEntities GetContext() => _ctx ?? (_ctx = new stayEntities());
        public stayEntities()
            : base("name=stayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direction> directions { get; set; }
        public virtual DbSet<entrant> entrants { get; set; }
        public virtual DbSet<mode> modes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<specialization> specializations { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<time> times { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
