//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stay
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class specialization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public specialization()
        {
            this.staffs = new HashSet<staff>();
        }

        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{image}";
            }
        }

        public int id_specialization { get; set; }
        public string name_specialization { get; set; }
        public int id_directions { get; set; }
        public double price { get; set; }
        public string budget { get; set; }
        public string paid { get; set; }
        public int id_staff { get; set; }
        public string image { get; set; }
        public int id_mode { get; set; }
        public string name_time { get; set; }
    
        public virtual direction direction { get; set; }
        public virtual mode mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff> staffs { get; set; }
    }
}
