//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stay
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int id_staff { get; set; }
        public int id_post { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string image { get; set; }
    
        public virtual post post { get; set; }
        public virtual specialization specialization { get; set; }
    }
}
