//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.zapis = new HashSet<zapis>();
        }

        public string GetPhoto
        {
            get
            {
                if (photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + photo.Trim();
            }
        }

        public int id_book { get; set; }
        public string book_name { get; set; }
        public string author { get; set; }
        public int year { get; set; }
        public string photo { get; set; }
        public int id_janre { get; set; }
        public int id_censure { get; set; }
    
        public virtual censure censure { get; set; }
        public virtual janre janre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapis> zapis { get; set; }
    }
}
