//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEEntities1 : DbContext
    {
        public libraryEEntities1()
            : base("name=libraryEEntities1")
        {
        }

        static private libraryEEntities1 _context;
        static public libraryEEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new libraryEEntities1();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<censure> censure { get; set; }
        public virtual DbSet<janre> janre { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<zapis> zapis { get; set; }
    }
}
