//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapis
    {
        public int id_zapis { get; set; }
        public int id_book { get; set; }
        public int id_user { get; set; }
        public System.DateTime time_start { get; set; }
        public System.DateTime time_end { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}
