//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Change
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Change()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public string GetPhoto
        {
            get
            {
                if (Photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Photo.Trim();
            }
        }

        public int ChangeID { get; set; }
        public int ChangeCategoryID { get; set; }
        public int ClientID { get; set; }
        public string Descr { get; set; }
        public System.DateTime DateChange { get; set; }
        public double MoneyHand { get; set; }
        public double Commissor { get; set; }
        public System.DateTime DateReturn { get; set; }
        public string Photo { get; set; }
    
        public virtual ChangeCategory ChangeCategory { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
