//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PawnShopEntities : DbContext
    {
        public PawnShopEntities()
            : base("name=PawnShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static PawnShopEntities _context;
        public static PawnShopEntities GetContext()
        {
            if (_context == null)
            {
                _context = new PawnShopEntities();
            }
            return _context;
        }

     
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Change> Changes { get; set; }
        public virtual DbSet<ChangeCategory> ChangeCategories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
