//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSt.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiEntities : DbContext
    {
        public TaxiEntities()
            : base("name=TaxiEntities")
        {
        }

        static private TaxiEntities _ctx;
        static public TaxiEntities GetContext() => _ctx ?? (_ctx = new TaxiEntities());

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taxi> Taxis { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vodila> Vodilas { get; set; }
    }
}
