//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSt.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public int Voditel_id { get; set; }
        public int Client_id { get; set; }
        public int OrderID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Vodila Vodila { get; set; }
    }
}
