//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSt.Modules
{
    using System;
    using System.IO;
    using System.Collections.Generic;
    
    public partial class Vodila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vodila()
        {
            this.Taxis = new HashSet<Taxi>();
        }

        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{Photo}";
            }
        }

        public int GetRndRider()
        {
            Random rnd = new Random();
            int RandomN = rnd.Next(Voditel_id);
            int rndRider = RandomN;
            return rndRider;
        }

        public int Voditel_id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public string Marka { get; set; }
        public double Reiting { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taxi> Taxis { get; set; }
    }
}
