//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storehouse.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int ProviiderID { get; set; }
        public int ProductTypeID { get; set; }
        public int AmountOnWH { get; set; }
        public string Photo { get; set; }


        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{Photo}";
            }
        }

        public virtual ProductType ProductType { get; set; }
        public virtual Proviider Proviider { get; set; }
    }
}
