//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosU.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public int PersonalID { get; set; }
        public int ServiceID { get; set; }
        public int HealthID { get; set; }
        public int SocialID { get; set; }
    
        public virtual Health Health { get; set; }
        public virtual PersonalData PersonalData { get; set; }
        public virtual Service Service { get; set; }
        public virtual SocialPosition SocialPosition { get; set; }
    }
}
