//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosU.Modules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialSupportEntities : DbContext
    {
        public SocialSupportEntities()
            : base("name=SocialSupportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        static private SocialSupportEntities _ctx;
        static public SocialSupportEntities GetContext() => _ctx ?? (_ctx = new SocialSupportEntities());

        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Health> Healths { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SocialPosition> SocialPositions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
