//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosU.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialPosition
    {

        public string GetFam
        {
            get
            {
                if (FamilyComp == 0)
                {
                    return "Неполная";
                }
                else if (FamilyComp == 1)
                {
                    return "Полная";
                }
                else
                {
                    return "Многодетная";
                }
            }
        }
        public int SocialID { get; set; }
        public string Pwork { get; set; }
        public Nullable<double> Income { get; set; }
        public string Post { get; set; }
        public int AmountOfChild { get; set; }
        public int FamilyComp { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
