//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanator.Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sanEntities : DbContext
    {
        public sanEntities()
            : base("name=sanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        static private sanEntities _ctx;
        static public sanEntities GetContext() => _ctx ?? (_ctx = new sanEntities());
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<feed> feeds { get; set; }
        public virtual DbSet<healing> healings { get; set; }
        public virtual DbSet<nomer> nomers { get; set; }
        public virtual DbSet<placement> placements { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tour> tours { get; set; }
        public virtual DbSet<type_nomer> type_nomer { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<view> views { get; set; }
    }
}
