//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanator.Module
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    
    public partial class healing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public healing()
        {
            this.tours = new HashSet<tour>();
        }

        public string GetPhoto
        {
            get
            {
                if (photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + photo.Trim();

            }
        }

        public int id_healing { get; set; }
        public string healing_name { get; set; }
        public double price { get; set; }
        public string photo { get; set; }
        public int id_view { get; set; }
        public int id_staff { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual view view { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour> tours { get; set; }
    }
}
