//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanator.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public int id_tour { get; set; }
        public int id_client { get; set; }
        public int id_healing { get; set; }
        public int id_nomer { get; set; }
    
        public virtual client client { get; set; }
        public virtual healing healing { get; set; }
        public virtual nomer nomer { get; set; }
    }
}
