//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumperApplication.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AgentId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Photo { get; set; } = "agent.png";
        public string Address { get; set; }
        public int Priority { get; set; }
        public string BossName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int AgentTypeId { get; set; }
        public int OrderAmount { get; set; }
        public double OrderSumm { get; set; }


        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{Photo}";
            }
        }

        public int GetSale
        {
            get
            {
                if (OrderSumm < 10000)
                {
                    return 0;
                }
                else if (OrderSumm < 50000)
                {
                    return 5;
                }
                else if (OrderSumm < 150000)
                {
                    return 10;
                }
                else if (OrderSumm < 500000)
                {
                    return 20;
                }
                else
                {
                    return 25;
                }

            }
        }

        public string GetColor
        {
            get
            {
                if (OrderSumm < 500000)
                    return "#ffffff";
                else
                    return "#98FB98"; 
            }
        }

        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
